### ISSUE TITLE
java.lang.NullPointerException: validateProjectPath(...) must not be null

### ISSUE THREAD

**Issue by hasunnilupul** [KartanHQ/intellij-nuxtjs#250] opened 2023-08-06 08:38 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
* Java: JetBrains s.r.o. 17.0.7
* OS: Windows 10 amd64
* IDE: WebStorm 2023.1.4
* Version: 2.0.2

**Additional context**

**Stacktrace**
null

**Comment by nekofar** [comment] 2023-08-14 09:43
Duplicate of #246

**Closed by nekofar** 2023-08-14 09:43 UTC
Labels: bug, duplicate
